      - name: Modify heiliao.sgmodule content
        run: |
          # æ›¿æ¢ç¬¬ä¸€è¡Œ
          sed -i '1s/.*/#!name= é»‘æ–™ä¸æ‰“çƒŠðŸ”ž/' Plugin/heiliao.sgmodule

          # æ’å…¥ä¸‰è¡Œåˆ°ç¬¬4è¡Œï¼ˆç¬¬3è¡ŒåŽï¼‰
          tmpfile=$(mktemp)
          awk 'NR==3 {
              print
              print "#!openUrl = https://155.fun"
              print "#!icon = https://raw.githubusercontent.com/fishdown/Icon/master/app/hlw.png"
              print "#!tag = 18"
              next
            } 1' Plugin/heiliao.sgmodule > "$tmpfile"
          mv "$tmpfile" Plugin/heiliao.sgmodule

          # è¿½åŠ  Rewrite å†…å®¹åˆ°æ–‡ä»¶æœ«å°¾
          echo '' >> Plugin/heiliao.sgmodule
          echo '[Rewrite]' >> Plugin/heiliao.sgmodule
          echo '#æœ€æ–°é»‘æ–™' >> Plugin/heiliao.sgmodule
          echo 'https:\/\/[^\/]+\/hlcg\/.* response-body-replace-regex </head> </head><style>.video-list>.video-item:nth-of-type(1),.video-list>.video-item:nth-of-type(2),.gotoclick,.modal,.addbox{display:none!important}</style>' >> Plugin/heiliao.sgmodule
          echo '#è¯¦æƒ…é¡µåŽ»å¹¿å‘Š' >> Plugin/heiliao.sgmodule
          echo '^https?://[^/]+/archives.* response-body-replace-regex </head> </head><style>.t_activity,.share-box,.video-list>.gotoclick,.modal,.addbox,.list-sec-top,#copy-img,.line,.list-sec,.infomation,.client-only-placeholder>blockquote,.article-tags,.relation,.footer,.plates,.dplayer>p:first-of-type,.dplayer~p,.common{display:none!important}</style>' >> Plugin/heiliao.sgmodule
